-- AlterTable
ALTER TABLE "History" ADD COLUMN     "anne" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "blacksmith" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "brick" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "col" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "elsa" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "librarian" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "lisa" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tom" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "log_groot" SET DEFAULT '';
